USE DATABASE ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

USE SCHEMA RAW;

DROP TABLE IF EXISTS CONTAINER_SENSOR_DATA;

CREATE TABLE CONTAINER_SENSOR_DATA (

    CONTAINER_ID STRING,
    SHIPMENT_ID STRING,
    FRUIT_TYPE STRING,
    ORIGIN STRING,
    DESTINATION STRING,

    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    VIBRATION FLOAT,
    BATTERY_LEVEL INTEGER,

    DOOR_STATUS STRING,
    CONTAINER_STATUS STRING,

    LATITUDE FLOAT,
    LONGITUDE FLOAT,

    TIMESTAMP TIMESTAMP,

    RISK_LEVEL STRING,
    BATTERY_STATUS STRING,
    TEMPERATURE_STATUS STRING,

    DATE DATE,
    HOUR INTEGER,

    ROUTE STRING

);
DESC TABLE RAW.CONTAINER_SENSOR_DATA;


