CREATE DATABASE ATMOSYNC_DB;

USE DATABASE ATMOSYNC_DB;

CREATE SCHEMA RAW;

USE SCHEMA RAW;

CREATE WAREHOUSE ATMOSYNC_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE ATMOSYNC_WH;

CREATE TABLE CONTAINER_SENSOR_DATA (
    ID INTEGER PRIMARY KEY,
    TIMESTAMP TIMESTAMP,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    PRESSURE FLOAT,
    CO2_GAS INTEGER,
    PM2_5 FLOAT,
    PM10 FLOAT,
    DAYTIME STRING
);